version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: fast-order-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fast_order
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data: