apiVersion: apps/v1
kind: Deployment
metadata:
  name: fo-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fo-cache
  template:
    metadata:
      labels:
        app: fo-cache
    spec:
      containers:
      - name: fo-cache
        image: redis:8.0-M02-alpine3.20
        resources:
          limits:
            memory: "2Gi"
            cpu: "100m"
          requests:
            memory: "512Mi"
            cpu: "10m"
        ports:
        - containerPort: 6379
      volumes:
      - name: config
        configMap:
          defaultMode: 0666
          name: redis-service-config
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim
