apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-dep
  labels:
    app: fast-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-crud
  template:
    metadata:
      labels:
        app: fast-crud
    spec:
      containers:
      - name: fast-order-cont
        image: bergzado/fast-order-app:0.0.7
        ports:
        - containerPort: 57399
        - containerPort: 57398
        envFrom:
          - configMapRef:
              name: fo-api-configmap
        livenessProbe:
          httpGet:
            path: /health
            port: 57398
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        resources:
            requests:
              cpu: 1m