apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlserver
  name: sqlserver
spec:
  ports:
    - name: "11433"
      port: 11433
      targetPort: 1433
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    app: sqlserver