apiVersion: v1
kind: Service
metadata:
  name: fast-crud-svc
spec:
  selector:
    app: fast-crud
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8080
      nodePort: 31500
    - port: 81
      name: https
      targetPort: 8081
      nodePort: 31600