apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastorder-webapi
  name: fastorder-webapi
spec:
  ports:
    - name: "57398"
      port: 57398
      targetPort: 57398
    - name: "57399"
      port: 57399
      targetPort: 57399
  selector:
    app: fastorder-webapi