apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postech8soat-fastorder-webapi
  name: postech8soat.fastorder.webapi
spec:
  ports:
    - name: "57398"
      port: 57398
      targetPort: 57398
    - name: "57399"
      port: 57399
      targetPort: 57399
  selector:
    io.kompose.service: postech8soat-fastorder-webapi
