apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postech8soat-fastorder-webapi
  name: postech8soat-fastorder-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postech8soat-fastorder-webapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postech8soat-fastorder-webapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: fiap@123
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /app/certs/fastorder.pfx
            - name: ASPNETCORE_URLS
              value: https://+:57399;http://+57398
          image: postech8soatfastorderwebapi
          name: postech8soat.fastorder.webapi
          ports:
            - containerPort: 57398
              protocol: TCP
            - containerPort: 57399
              protocol: TCP
          volumeMounts:
            - mountPath: /app/certs
              name: postech8soat-fastorder-webapi-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: postech8soat-fastorder-webapi-cm0
          name: postech8soat-fastorder-webapi-cm0
