apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sql-data
  name: sql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
